[package]
name = "gibberish-models"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
reqwest = { version = "0.12", features = ["stream"] }
futures.workspace = true
thiserror.workspace = true
tracing.workspace = true
dirs.workspace = true
