[package]
name = "gibberish-application"
version.workspace = true
edition.workspace = true

[dependencies]
gibberish-stt.workspace = true
gibberish-vad.workspace = true
gibberish-turn.workspace = true
thiserror.workspace = true
tracing.workspace = true
hound.workspace = true
