[package]
name = "gibberish-stt"
version.workspace = true
edition.workspace = true

[dependencies]
hound.workspace = true
whisper-rs.workspace = true
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
